disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - force_cast
  - identifier_name
  - file_length
  - line_length
  - type_name
  - todo
  - private_over_fileprivate
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
