excluded: # paths to ignore during linting.
  - Pods
  - Carthage
disabled_rules: # rule identifiers turned on by default to exclude from running
  - closure_parameter_position
  - force_cast
  - file_length
  - line_length
  - todo
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
analyzer_rules:
  - unsed_import
identifier_name:
  allowed_symbols: '_'
  validates_start_with_lowercase: false
  min_length:
    warning: 1
  max_length:
    warning: 100
vertical_whitespace:
  max_empty_lines: 2
