
# iOS CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  build-and-test:
    macos:
      xcode: "12.2"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
          name: Set Ruby version
          command: echo "ruby-2.6" > ~/.ruby-version
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Install dependencies in Gemfile
          command: bundle install
      - run:
          name: Install CocoaPods
          command: bundle exec pod update #--verbose
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: GiftHunteriOS

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 1
  build-and-test:
    jobs:
      - build-and-test
